# Site settings
title: "Reactor Tutorial"
description: "In-depth dissection of Reactive Programming Internal Working"
url: "https://ramnull.github.io"   # your GitHub Pages URL
# baseurl: "/reactor"              # leave commented, GitHub handles it

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..3                 # ensures IDs for h1–h3 (used by sidebar TOC)
highlighter: rouge

# Theme
remote_theme: pages-themes/cayman@v0.2.0

# Plugins (safe for GitHub Pages)
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag                 # you’re already using {% seo %} in layout

# Include and exclude
include: ["*.md"]
exclude: ["README.md"]

# Permalinks
permalink: /:title.html            # reactive-programming.md -> reactive-programming.html

# Social / Links
linkedin: "https://www.linkedin.com/in/sriram-nallas"
author: "Sriram Nalla"            # optional, used in footer if you want
show_downloads: false              # matches layout button condition
