# /docs/_config.yml

# Site settings
title: "Reactor Tutorial"
description: "Documentation for Reactive Programming"
url: "https://ramnull.github.io"  # your GitHub Pages URL
# baseurl: "/reactor"   # DO NOT set baseurl, GitHub automatically handles repo name

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Include and exclude
include: ["*.md"]
exclude: ["README.md"]

# Permalinks
permalink: /:title.html   # ensures reactive-programming.md -> reactive-programming.html

# Optional: Enable syntax highlighting for code blocks
# Example usage in markdown: ```ruby ... ```

github: "https://github.com/ramnull"
linkedin: "https://www.linkedin.com/in/sriram-nallas"
