name: Copilot Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - main
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  # Job 1: Initial review when PR is opened or updated
  review-pr:
    name: Review Pull Request
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup GitHub CLI
        run: |
          # GitHub CLI is pre-installed on ubuntu-latest
          gh --version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Make review script executable
        run: chmod +x .github/scripts/review-pr.sh
      
      - name: Run code review
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: |
          .github/scripts/review-pr.sh "$PR_NUMBER"

  # Job 2: Handle responses to review comments
  handle-response:
    name: Handle Review Response
    if: |
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      !contains(github.event.comment.body, '🤖') &&
      github.event.comment.user.login != 'github-actions[bot]'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup GitHub CLI
        run: |
          gh --version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Make response handler script executable
        run: chmod +x .github/scripts/handle-review-response.sh
      
      - name: Process committer response
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_ID: ${{ github.event.comment.id }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          PR_NUMBER: ${{ github.event.issue.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          .github/scripts/handle-review-response.sh "$COMMENT_ID" "$COMMENT_BODY" "$PR_NUMBER"
      
      - name: Make resolution script executable
        run: chmod +x .github/scripts/resolve-review.sh
      
      - name: Check if review should be resolved
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
          COMMENT_ID: ${{ github.event.comment.id }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          .github/scripts/resolve-review.sh "$PR_NUMBER" "$COMMENT_ID"
