# Workflow: Deploy Jekyll site from /docs
# This workflow builds and deploys all markdown files in /docs including:
# - index.md -> https://ramnull.github.io/reactor/
# - working-example.md -> https://ramnull.github.io/reactor/example
name: Deploy Jekyll from /docs

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build Jekyll site from /docs
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs       # <-- use /docs as Jekyll source
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
